version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  app:
    build: ./server
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/myapp
    ports:
      - "8080:3000"
    depends_on:
      - postgres
  
  client:
    image: node:10.16.3
    restart: always
    working_dir: /code
    volumes: 
      - ./client:/code
    ports: 
      - "80:3000"
    command: yarn prod
    depends_on: 
      - postgres
      - app
    environment: 
      BACKEND_URL: "http://app:8080/graphql"

volumes: 
    postgres_volume: