version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  app:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "4000:3000"
    depends_on:
      - postgres
  
  client:
    build: ./client
    restart: always
    ports: 
      - "3000:3000"
    depends_on: 
      - postgres
      - app

volumes: 
    postgres_volume: